/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class hotel extends javax.swing.JFrame {
int hekonomi, hvip;
    /**
     * Creates new form awal
     */
    public hotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        rvip = new javax.swing.JRadioButton();
        rekonomi = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tglhotel = new datechooser.beans.DateChooserCombo();
        cmbhotel = new javax.swing.JComboBox<>();
        cmbdurasi = new javax.swing.JComboBox<>();
        cmbtamu = new javax.swing.JComboBox<>();
        namahotel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        resethotel = new javax.swing.JButton();
        prosesh = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        hitunghotel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        proseshotel = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rvip.setText("VIP");
        rvip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rvipActionPerformed(evt);
            }
        });
        jPanel2.add(rvip, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 50, -1));

        rekonomi.setText("Ekonomi");
        rekonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rekonomiActionPerformed(evt);
            }
        });
        jPanel2.add(rekonomi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 70, -1));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Jumlah Tamu");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Check In");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));
        jPanel2.add(tglhotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 140, -1));

        cmbhotel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Hotel", "Hotel Grand Mahkota", "Hotel California" }));
        cmbhotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbhotelActionPerformed(evt);
            }
        });
        jPanel2.add(cmbhotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 140, 20));

        cmbdurasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Durasi", "1 Malam", "2 Malam", "3 Malam" }));
        cmbdurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdurasiActionPerformed(evt);
            }
        });
        jPanel2.add(cmbdurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 140, 20));

        cmbtamu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jumlah", "1", "2", "3" }));
        cmbtamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtamuActionPerformed(evt);
            }
        });
        jPanel2.add(cmbtamu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 130, -1));

        namahotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namahotelActionPerformed(evt);
            }
        });
        jPanel2.add(namahotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 140, -1));

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Nama");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Harga");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        resethotel.setText("Reset");
        resethotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resethotelActionPerformed(evt);
            }
        });
        jPanel2.add(resethotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        prosesh.setFont(new java.awt.Font("Intro ", 0, 11)); // NOI18N
        prosesh.setForeground(new java.awt.Color(0, 0, 153));
        prosesh.setText("Print tiket");
        jPanel2.add(prosesh, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 430, 80, 20));

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Total Harga");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        jLabel16.setFont(new java.awt.Font("Intro ", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(242, 242, 242));
        jLabel16.setText("kembali ke menu");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\nama kecik.jpg")); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 40, 50));

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        jPanel2.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 150, 30));

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        jPanel2.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 150, 30));

        hitunghotel.setText("Hitung");
        hitunghotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitunghotelActionPerformed(evt);
            }
        });
        jPanel2.add(hitunghotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\biru.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 160, 20));

        proseshotel.setForeground(new java.awt.Color(242, 242, 242));
        proseshotel.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\abu.jpg")); // NOI18N
        proseshotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proseshotelActionPerformed(evt);
            }
        });
        jPanel2.add(proseshotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 160, 20));

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Durasi");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Pilih Hotel");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 50, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\bulan icon.jpg")); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 50, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\kalender icon.jpg")); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 60, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\orang icon.jpg")); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 80, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\hotel icon.jpg")); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 40, 50));

        jLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Booking Hotel & Tiket Penerbangan");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 220, 50));
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\produk kecik.jpg")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 350, 100));

        jLabel5.setFont(new java.awt.Font("Intro ", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(244, 244, 244));
        jLabel5.setText("booking hotel");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\biru.jpg")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 440, 30));

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbhotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbhotelActionPerformed
    if (cmbhotel.getSelectedItem().equals("Pilih Hotel")) {
        bg2.clearSelection();
        txtharga.setText("");
    }   else if (cmbhotel.getSelectedItem().equals("Hotel Grand Mahkota")) {
       hekonomi  = 450000;
       hvip    = 1000000;
    } else if (cmbhotel.getSelectedItem().equals("Hotel California")) {
       hekonomi  = 600000;
       hvip    = 1200000;
    }
    }//GEN-LAST:event_cmbhotelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        menu m = new menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void proseshotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proseshotelActionPerformed
        // TODO add your handling code here:
        String Namaa = namahotel.getText();
        String Hotel = (String) cmbhotel.getSelectedItem();
        String Durasi = (String) cmbdurasi.getSelectedItem();
        String Tamu = (String) cmbtamu.getSelectedItem();
        String Harga = txtharga.getText();
        String Total = txttotal.getText();
        bookinghotel bo = new bookinghotel(Namaa, Hotel, Durasi, Tamu, Harga, Total);
        bo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_proseshotelActionPerformed

    private void namahotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namahotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namahotelActionPerformed

    private void cmbdurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdurasiActionPerformed
    if (cmbhotel.getSelectedItem().equals("Pilih Hotel")) {
        bg2.clearSelection();
        txtharga.setText("");
    }   else if (cmbhotel.getSelectedItem().equals("Hotel Grand Mahkota")) {
       hekonomi  = 450000;
       hvip    = 1000000;
    } else if (cmbhotel.getSelectedItem().equals("Hotel California")) {
       hekonomi  = 600000;
       hvip    = 1200000;
    } 
    
    }//GEN-LAST:event_cmbdurasiActionPerformed

    private void cmbtamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtamuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtamuActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
    String Namaa = namahotel.getText();
        String Hotel = (String) cmbhotel.getSelectedItem();
        String Durasi = (String) cmbdurasi.getSelectedItem();
        String Tamu = (String) cmbtamu.getSelectedItem();
        String Harga = txtharga.getText();
        String Total = txttotal.getText();
        bookinghotel b = new bookinghotel(Namaa, Hotel, Durasi, Tamu, Harga, Total);
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txttotalActionPerformed

    private void rekonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rekonomiActionPerformed
    if (rekonomi.isSelected()) {
        txtharga.setText(String.valueOf(hekonomi)); 
    }
    }//GEN-LAST:event_rekonomiActionPerformed

    private void resethotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resethotelActionPerformed
     cmbhotel.removeAllItems();
     cmbtamu.removeAllItems();
     cmbdurasi.removeAllItems();
     txtharga.setText("");
     txttotal.setText("");
    }//GEN-LAST:event_resethotelActionPerformed

    private void hitunghotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitunghotelActionPerformed
        // TODO add your handling code here:
       String durasi = String.valueOf(cmbdurasi.getSelectedIndex());
        int lamasewa = Integer.parseInt(durasi);
        int hargakamar = Integer.parseInt(txtharga.getText());
        int totalbayar = lamasewa*hargakamar;
        txttotal.setText(""+totalbayar);
    }//GEN-LAST:event_hitunghotelActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void rvipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rvipActionPerformed
    if (rvip.isSelected()) {
        txtharga.setText(String.valueOf(hvip));
    }//GEN-LAST:event_rvipActionPerformed
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg2;
    private javax.swing.JComboBox<String> cmbdurasi;
    private javax.swing.JComboBox<String> cmbhotel;
    private javax.swing.JComboBox<String> cmbtamu;
    private javax.swing.JButton hitunghotel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namahotel;
    private javax.swing.JLabel prosesh;
    private javax.swing.JButton proseshotel;
    private javax.swing.JRadioButton rekonomi;
    private javax.swing.JButton resethotel;
    private javax.swing.JRadioButton rvip;
    private datechooser.beans.DateChooserCombo tglhotel;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
