/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class pesawat extends javax.swing.JFrame {
int hanak, hdewasa, harga, total;
    /**
     * Creates new form awal
     */
    public pesawat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rddewasa = new javax.swing.JRadioButton();
        rdanak = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        tgl = new datechooser.beans.DateChooserCombo();
        cmbsawat = new javax.swing.JComboBox<>();
        cmbtujuansawat = new javax.swing.JComboBox<>();
        cmborang = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        proses = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Nama");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\nama kecik.jpg")); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 40, 40));

        bg.add(rddewasa);
        rddewasa.setText("Dewasa");
        rddewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rddewasaActionPerformed(evt);
            }
        });
        jPanel2.add(rddewasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        rdanak.setText("Anak");
        rdanak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdanakActionPerformed(evt);
            }
        });
        jPanel2.add(rdanak, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Jumlah Penumpang");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Check In");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel13.setBackground(new java.awt.Color(242, 242, 242));
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Total Harga");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 70, 20));

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        jPanel2.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 150, 30));
        jPanel2.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 150, -1));

        cmbsawat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Maskapai", "Pesawat Lion Air", "Pesawat Garuda" }));
        cmbsawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsawatActionPerformed(evt);
            }
        });
        jPanel2.add(cmbsawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 150, 20));

        cmbtujuansawat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tujuan", "Pontianak - Jakarta", "Pontianak - Bandung", "Jakarta - Jayapura" }));
        cmbtujuansawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtujuansawatActionPerformed(evt);
            }
        });
        jPanel2.add(cmbtujuansawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 150, 20));

        cmborang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jumlah", "1", "2", "3", " " }));
        cmborang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmborangActionPerformed(evt);
            }
        });
        jPanel2.add(cmborang, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 130, -1));

        jLabel15.setFont(new java.awt.Font("Intro ", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 153));
        jLabel15.setText("print tiket");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, 20));

        jLabel16.setFont(new java.awt.Font("Intro ", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(242, 242, 242));
        jLabel16.setText("kembali ke menu");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, 20));

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\biru.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 160, 20));

        proses.setForeground(new java.awt.Color(242, 242, 242));
        proses.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\abu.jpg")); // NOI18N
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        jPanel2.add(proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 170, 20));

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Tujuan");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel2.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 150, -1));

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Pilih Maskapai");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\lokasi icon.jpg")); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 50, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\kalender icon.jpg")); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 60, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\orang icon.jpg")); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 60, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\sawat kecik.jpg")); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 40, 50));

        jLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Booking Hotel & Tiket Penerbangan");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 220, 50));
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\produk kecik.jpg")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 350, 100));

        jLabel5.setFont(new java.awt.Font("Intro ", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(244, 244, 244));
        jLabel5.setText("TIKET PESAWAT");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 150, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Bahan Project Analog\\biru.jpg")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 440, 30));

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        jPanel2.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 150, 30));

        jLabel17.setBackground(new java.awt.Color(242, 242, 242));
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Harga");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 50, 20));

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        jPanel2.add(hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbsawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsawatActionPerformed
    
    }//GEN-LAST:event_cmbsawatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        menu m = new menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbtujuansawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtujuansawatActionPerformed
    if (cmbtujuansawat.getSelectedItem().equals("Pilih Tujuan")) {
        bg.clearSelection();
        txtharga.setText("");
    }   else if (cmbtujuansawat.getSelectedItem().equals("Pontianak - Jakarta")) {
       hdewasa  = 400000;
       hanak    = 200000;
    } else if (cmbtujuansawat.getSelectedItem().equals("Pontianak - Bandung")) {
       hdewasa  = 500000;
       hanak    = 250000;
    } else if (cmbtujuansawat.getSelectedItem().equals("Jakarta - Jayapura")) {
        hdewasa = 600000;
        hanak   = 300000;
    }
    }//GEN-LAST:event_cmbtujuansawatActionPerformed

    private void cmborangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmborangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmborangActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        String Namaa = nama.getText();
        String Maskapai = (String) cmbsawat.getSelectedItem();
        String Tujuan = (String) cmbtujuansawat.getSelectedItem();
        String Jumlah = (String) cmborang.getSelectedItem();
        String Harga = txtharga.getText();
        String Total = txttotal.getText();
        tiketsawat t = new tiketsawat(Namaa, Maskapai, Tujuan, Jumlah, Harga, Total);
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prosesActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
//    cmbtujuansawat.getSelectedItem();
    }//GEN-LAST:event_txttotalActionPerformed

    private void rdanakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdanakActionPerformed
    if (rdanak.isSelected()) {
        txtharga.setText(String.valueOf(hanak));
    }
    }//GEN-LAST:event_rdanakActionPerformed

    private void rddewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rddewasaActionPerformed
    if (rddewasa.isSelected()) {
        txtharga.setText(String.valueOf(hdewasa));
    }
    }//GEN-LAST:event_rddewasaActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
        cmbtujuansawat.getSelectedItem();
    }//GEN-LAST:event_txthargaActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        String orang = String.valueOf(cmborang.getSelectedIndex());
        int penumpang = Integer.parseInt(orang);
        int harga = Integer.parseInt(txtharga.getText());
        int total = (harga*penumpang);
        txttotal.setText(""+total);
    }//GEN-LAST:event_hitungActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        cmbsawat.removeAllItems();
        cmborang.removeAllItems();
        cmbtujuansawat.removeAllItems();
        txtharga.setText("");
        txttotal.setText("");
        
        
    }//GEN-LAST:event_resetActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pesawat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JComboBox<String> cmborang;
    private javax.swing.JComboBox<String> cmbsawat;
    private javax.swing.JComboBox<String> cmbtujuansawat;
    private javax.swing.JButton hitung;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nama;
    private javax.swing.JButton proses;
    private javax.swing.JRadioButton rdanak;
    private javax.swing.JRadioButton rddewasa;
    private javax.swing.JButton reset;
    private datechooser.beans.DateChooserCombo tgl;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
